name: Ecosystem

# on:
#   schedule:
#    - cron: "0 0 * * *" # everyday
# TODO: remove this
on:
  push:
  #   branches: [ main ]
  # pull_request:

permissions:
  contents: read
  checks: write

jobs:
  build-chicory:
    name: Prepare Chicory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Chicory sources
        uses: actions/checkout@v4
        with:
          repository: dylibso/chicory
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Build Chicory
        run: ./mvnw -B -Dquickly
      - name: Upload .m2 repo for reuse
        uses: actions/upload-artifact@v4
        with:
          name: m2-repo
          path: ~/.m2/repository

  ecosystem:
    name: Ecosystem CI
    needs: build-chicory
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        project:
          - StyraInc/opa-java-wasm
          - roastedroot/sqlite4j
          - roastedroot/quickjs4j
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          path: ecosystem-ci
      - name: Checkout ${{ matrix.project }} sources
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.project }}
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Restore .m2 repo
        uses: actions/download-artifact@v4
        with:
          name: m2-repo
          path: ~/.m2/repository
      - name: Replace Java version
        run: |
          sed -i "s|<chicory.version>.*</chicory.version>|<chicory.version>999-SNAPSHOT</chicory.version>|" pom.xml

      # Ecosystem project specific setup

      # opa-java-wasm
      - name: Checkout OPA
        if: matrix.project == 'StyraInc/opa-java-wasm'
        uses: actions/checkout@v4
        with:
          repository: open-policy-agent/opa
          ref: main
          path: opa-testcases
      - name: Prep OPA cases
        if: matrix.project == 'StyraInc/opa-java-wasm'
        working-directory: opa-testcases
        run: |
          WASM_BUILD_ONLY=true make wasm-rego-test
          cp .go/cache/testcases.tar.gz ../
      - name: Install Open Policy Agent
        if: matrix.project == 'StyraInc/opa-java-wasm'
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 0.70.0

      # QuickJs4J
      - name: Set up Rust
        if: matrix.project == 'roastedroot/quickjs4j'
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build the Javy plugin
        if: matrix.project == 'roastedroot/quickjs4j'
        working-directory: javy-plugin
        run: |
          rustup target add wasm32-wasip1
          make build

      # Common install and test for projects

      - name: Test Java
        run: mvn -B clean install -Dspotless.check.skip=true

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Sanity check
        run: ./ecosystem-ci/scripts/check-versions.sh
